### PR TITLE
Don't reset DPMS settings if DIMMER is disabled

### LINKED ISSUE #121: [BUG] disabled module still enforces configuration options
**Clight version the issue has been seen with:**
`devel` branch, commit id 1a6b6fd2d5a5d044289c4a3c8f5702ed25f2b0bf

**Used distribution:**
Gentoo

**Describe the bug**
While testing `devel` branch related to #120, I noticed that setting a shorter DPMS timeout than the dimmer timeout causes clight to say

> DPMS AC timeout: wrong value (<= dimmer timeout). Resetting default value.

 _even with the dimmer disabled_.

**Expected behavior**
I expected a disabled module wouldn't have any effect on the enabled modules' configuration (nice to have a message about that, though :+1: ).

**To Reproduce**
1. build clight from commit 1a6b6fd2d5a5d044289c4a3c8f5702ed25f2b0bf
1. edit devel config to
    - disable dimmer with uncommenting `disabled = true` in the dimmer section
    - set DPMS timeouts to `timeouts = [ 30, 30 ];` in the DPMS section (note that this is shorter than the default dimmer `timeouts = [ 45, 20 ];`)
 1. start clight with that config file and read the printed output

Verbose log:
[clight.log](https://github.com/FedeDP/Clight/files/4528392/clight.log)

### PR DESCRIPTION
**Pull request by ferki**
This PR is a quick attempt to fix #121. It makes sure that a disabled DIMMER module does not have a side effect on the settings of the DPMS module.

@FedeDP: hope it's a good enough fix like that, let me know if you had something else in mind!

### CODE REVIEW

File: src/conf/opts.c [hunk 1]
```diff
@@ -384,12 +384,12 @@ static void check_dpms_conf(dpms_conf_t *dpms_conf) {
         dpms_conf->disabled = true;
     }
     
-    if (dpms_conf->timeout[ON_AC] <= conf.dim_conf.timeout[ON_AC]) {
+    if (!conf.dim_conf.disabled && dpms_conf->timeout[ON_AC] <= conf.dim_conf.timeout[ON_AC]) {
```
Comment (FedeDP) [inline src/conf/opts.c:387]: I'd rather make an unique check instead of checking if dim is enabled twice, ie: 
```
if (!conf.dim_conf.disabled) { 
    if (dpms_conf->timeout[ON_AC ...) { ... } 
    if (dpms_conf->timeout[ON_BATTERY] { ... } 
}
```

**Comment by FedeDP** [comment]
Thanks for this first try :) Just a small change and it is super good!

File: src/conf/opts.c (hunk 1 above)
Comment (ferki) [reply src/conf/opts.c:387]: Ha, that was exactly my first idea, but then I decided to keep the checks atomic ^^

I'll update the PR in a bit!

**Comment by FedeDP** [comment]
That's great!! Thank you very much for all your PRs, they're much appreciated :)
